# Generated by Django 3.1.5 on 2021-02-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_genre',
            field=models.CharField(choices=[('HO', 'Horror'), ('CO', 'Comedy'), ('WE', 'Western'), ('RO', 'Romantic'), ('AC', 'Action')], default='Horror', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='second_genre',
            field=models.CharField(choices=[('HO', 'Horror'), ('CO', 'Comedy'), ('WE', 'Western'), ('RO', 'Romantic'), ('AC', 'Action')], default='Horror', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='third_genre',
            field=models.CharField(choices=[('HO', 'Horror'), ('CO', 'Comedy'), ('WE', 'Western'), ('RO', 'Romantic'), ('AC', 'Action')], default='Horror', max_length=2),
        ),
    ]
