# Generated by Django 3.1.5 on 2021-02-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210202_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_genre',
            field=models.CharField(choices=[('HO', 'Horror'), ('CO', 'Comedy'), ('WE', 'Western'), ('RO', 'Romantic'), ('AC', 'Action')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_genre',
            field=models.CharField(choices=[('HO', 'Horror'), ('CO', 'Comedy'), ('WE', 'Western'), ('RO', 'Romantic'), ('AC', 'Action')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_genre',
            field=models.CharField(choices=[('HO', 'Horror'), ('CO', 'Comedy'), ('WE', 'Western'), ('RO', 'Romantic'), ('AC', 'Action')], max_length=50),
        ),
    ]
